### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by Japistos** [raguay/DuplicateFileDir#4]
After duplicating a folder using your plugin and then diving inside the folder, if I jump back out and then try to rename or delete the folder, I get an access denied permission error.
I experience the same problem if trying to use Windows Explorer to rename or delete the folder. 
If I rename the folder before diving inside the directory, it works as expected.

**Comment by raguay** [comment]
It sounds like Windows is keeping a lock to the folder. If you exit fman and reload, I bet you can edit it all you want. If not, then something else is going on.

If it is keeping a lock on it, then it is something particular to Windows. It doesn't have that behavior on macOS or Linux. I'll look into it.
