### ISSUE TITLE
Refresh folder view after duplicating

### ISSUE THREAD

**Issue by ikost** [raguay/DuplicateFileDir#5]
When folder is duplicated I have to go one level higher and get into the folder again to see the actual copy created by the plugin. Can you please add refresh of the folder list after duplicating to avoid that? Generally it would be also nice to ask for the new name of the folder instead of the autonaming "folder - Copy" or something like this with the other shortcut.

**Comment by ikost** [comment]
Dear Richard,

I have waited for 10s and the copy of the folder does not come out (win 10) in the current path. It does not refresh at all i guess! Can it be related to the duplicating of the folder and not the files?
My use case it to take a folder with some template files and duplicate it with the new name according to the content I will add there. Probably I have to try to fork your plugin and try myself...

Ilya

**Comment by ikost** [comment]
Ok. I guess the problem is the _copytree_ from **shutil**. Fman does not recommend to use Python's copy function due to no caching and provide internal _copy_ function, which I guess should start the refresh. [LINK](https://fman.io/docs/api#prepare_copy)

**Comment by raguay** [comment]
Well, it not showing the new file has to do with fman on Windows. On my
mac, it work fine. But, I don't have a Windows system right now to test on.
Sorry. There is nothing the plugin can do to refresh the display. It is
just what fman does (or suppose to do) automatically.

Yes, that would be a template maker functionality. Not what this was
designed for. But, my Script Launcher plugin allows you to create script
for doing things like that. You might check it out.

**Comment by raguay** [comment]
You must have an old copy of the plugin. I updated it a while ago to use
only fmans functions.

**Comment by ikost** [comment]
Thank you for recommending the Script Launcher. Will try for sure.

Hm. I am looking into the raw file here on the github.
Here is the code with shutil copytree function:
`newDir = filepath + "-copy"
copytree(filepath, newDir)`
Where do I get the updated plugin than?

**Comment by raguay** [comment]
yep, I forgot to push it. It should now have the correct version there.
Sorry. You will have to delete the plugin and re-install it.
